# Build stage
FROM node:20-alpine as dev

WORKDIR /app

# Context is smart-procure/
COPY frontend/package.json .

RUN npm install

COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
