# Build stage
FROM docker.1ms.run/node:20-alpine as dev

WORKDIR /app

# Context is smart-procure/
COPY frontend/package.json .

RUN npm install

COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
